# Generated by Django 6.0.6 on 2026-08-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('kind', models.CharField(choices=[('input', 'Farm Input'), ('produce', 'Produce')], max_length=20)),
                ('category', models.CharField(choices=[('seed', 'Seeds & Planting Material'), ('fertilizer', 'Fertilisers & Soil Amendments'), ('crop_protection', 'Crop Protection'), ('tool', 'Tools & Equipment'), ('irrigation', 'Irrigation'), ('protective_equipment', 'Protective Equipment'), ('grain', 'Grains & Cereals'), ('tuber', 'Roots & Tubers'), ('legume', 'Legumes & Pulses'), ('vegetable', 'Vegetables'), ('fruit', 'Fruits'), ('cash_crop', 'Cash Crops')], max_length=32)),
                ('description', models.TextField(help_text='A couple of practical sentences for the farmer.')),
                ('unit', models.CharField(blank=True, help_text="How it is sold, e.g. '50 kg bag' or 'per kg'.", max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_url', models.URLField(blank=True, help_text='Used when no image file is uploaded.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'category', 'name'],
                'indexes': [models.Index(fields=['kind', 'category'], name='products_pr_kind_5c3877_idx')],
            },
        ),
    ]
