# Generated by Django 6.0.6 on 2026-08-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_credit',
            field=models.CharField(blank=True, help_text="Attribution required by the photo's licence. Show it wherever the image is displayed.", max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Freely-licensed photo, used in preference to a generated card.'),
        ),
    ]
