# Generated by Django 6.0.6 on 2026-08-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_imageless_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text="Cached per-language text, e.g. {'fr': {'name': ..., 'description': ..., 'unit': ...}}."),
        ),
    ]
