# Generated by Django 6.0.6 on 2026-08-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='translations_source',
            field=models.CharField(blank=True, help_text='Fingerprint of the English text the cached translations were made from. When it stops matching, the translations are stale and get redone.', max_length=64),
        ),
    ]
