# Generated by Django 6.0.6 on 2026-08-20 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('XOF', 'CFA Franc BCEAO (XOF)'), ('XAF', 'CFA Franc BEAC (XAF)'), ('NGN', 'Nigerian Naira (NGN)'), ('GHS', 'Ghanaian Cedi (GHS)'), ('KES', 'Kenyan Shilling (KES)'), ('UGX', 'Ugandan Shilling (UGX)'), ('TZS', 'Tanzanian Shilling (TZS)'), ('RWF', 'Rwandan Franc (RWF)'), ('ZAR', 'South African Rand (ZAR)'), ('ETB', 'Ethiopian Birr (ETB)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)')], max_length=3, unique=True)),
                ('bank_name', models.CharField(max_length=120)),
                ('account_name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=64)),
                ('swift_or_iban', models.CharField(blank=True, max_length=64)),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('cash_contact_name', models.CharField(blank=True, max_length=120)),
                ('cash_contact_phone', models.CharField(blank=True, max_length=32)),
                ('instructions', models.TextField(blank=True, help_text='Extra guidance shown to the farmer.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['currency'],
            },
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('trial', 'Free Trial'), ('basic', 'Basic'), ('pro', 'Pro')], max_length=20)),
                ('currency', models.CharField(choices=[('XOF', 'CFA Franc BCEAO (XOF)'), ('XAF', 'CFA Franc BEAC (XAF)'), ('NGN', 'Nigerian Naira (NGN)'), ('GHS', 'Ghanaian Cedi (GHS)'), ('KES', 'Kenyan Shilling (KES)'), ('UGX', 'Ugandan Shilling (UGX)'), ('TZS', 'Tanzanian Shilling (TZS)'), ('RWF', 'Rwandan Franc (RWF)'), ('ZAR', 'South African Rand (ZAR)'), ('ETB', 'Ethiopian Birr (ETB)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)')], default='XOF', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Price for one period.', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['currency', 'plan'],
                'unique_together': {('plan', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('trial', 'Free Trial'), ('basic', 'Basic'), ('pro', 'Pro')], max_length=20)),
                ('months', models.PositiveSmallIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('XOF', 'CFA Franc BCEAO (XOF)'), ('XAF', 'CFA Franc BEAC (XAF)'), ('NGN', 'Nigerian Naira (NGN)'), ('GHS', 'Ghanaian Cedi (GHS)'), ('KES', 'Kenyan Shilling (KES)'), ('UGX', 'Ugandan Shilling (UGX)'), ('TZS', 'Tanzanian Shilling (TZS)'), ('RWF', 'Rwandan Franc (RWF)'), ('ZAR', 'South African Rand (ZAR)'), ('ETB', 'Ethiopian Birr (ETB)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)')], default='XOF', max_length=3)),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Price at the time of declaration, for spotting under/overpayment.', max_digits=12, null=True)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Bank transfer reference or cash receipt number.', max_length=120)),
                ('proof', models.ImageField(blank=True, null=True, upload_to='payments/proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Staff member who collected the money. Null when the farmer declared it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='subscriptio_status_23fc02_idx')],
            },
        ),
    ]
