# Generated by Django 6.0.6 on 2026-06-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='farm_latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='farm_longitude',
        ),
    ]
