# Generated by Django 6.0.6 on 2026-06-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_farm_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('admin', 'Admin'), ('appmanager', 'App Manager')], default='farmer', max_length=10),
        ),
    ]
