# Generated by Django 6.0.6 on 2026-06-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_history_notifications_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('sw', 'Swahili'), ('ha', 'Hausa'), ('yo', 'Yoruba'), ('ig', 'Igbo'), ('am', 'Amharic'), ('zu', 'Zulu'), ('xh', 'Xhosa'), ('tw', 'Twi'), ('wo', 'Wolof'), ('ln', 'Lingala'), ('sn', 'Shona'), ('dyu', 'Dioula'), ('bci', 'Baoulé'), ('bm', 'Bambara'), ('ff', 'Fulani')], default='en', max_length=5),
        ),
    ]
