# Generated by Django 6.0.6 on 2026-07-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_african_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('sw', 'Swahili'), ('ha', 'Hausa'), ('yo', 'Yoruba'), ('ig', 'Igbo'), ('am', 'Amharic'), ('zu', 'Zulu'), ('xh', 'Xhosa'), ('tw', 'Twi'), ('wo', 'Wolof'), ('ln', 'Lingala'), ('sn', 'Shona'), ('dyu', 'Dioula'), ('bci', 'Baoulé'), ('bm', 'Bambara'), ('ff', 'Fulani'), ('es', 'Spanish'), ('pt', 'Portuguese')], default='en', max_length=5),
        ),
    ]
